lib/hexpm_web/router.ex
defmodule HexpmWeb.Router do
  use HexpmWeb, :router
  use Plug.ErrorHandler
  alias Hexpm.Accounts.{Organization, User}

  @accepted_formats ~w(json elixir erlang)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :web_user_agent
    plug :validate_url
    plug :login
    plug :disable_deactivated
    plug :default_repository
  end

  pipeline :upload do
    plug :read_body_finally
    plug :accepts, @accepted_formats
    plug :user_agent
    plug :authenticate
    plug :disable_deactivated
    plug :validate_url
    plug HexpmWeb.Plugs.Attack
    plug :fetch_body
    plug :default_repository
  end

  pipeline :api do
    plug :accepts, @accepted_formats
    plug :user_agent
    plug :authenticate
    plug :disable_deactivated
    plug :validate_url
    plug HexpmWeb.Plugs.Attack
    plug Corsica, origins: "*", allow_methods: ["HEAD", "GET"]
    plug :default_repository
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", HexpmWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/pricing", PageController, :pricing
    get "/sponsors", PageController, :sponsors

    get "/login", LoginController, :show
    post "/login", LoginController, :create
    post "/logout", LoginController, :delete

    get "/signup", SignupController, :show
    post "/signup", SignupController, :create

    get "/password/new", PasswordController, :show
    post "/password/new", PasswordController, :update

    get "/password/reset", PasswordResetController, :show
    post "/password/reset", PasswordResetController, :create

    get "/email/verify", EmailVerificationController, :verify
    get "/email/verification", EmailVerificationController, :show
    post "/email/verification", EmailVerificationController, :create

    get "/dashboard", DashboardController, :index

    get "/users/:username", UserController, :show

    get "/orgs/:username", UserController, :show

    get "/docs", DocsController, :index
    get "/docs/usage", DocsController, :usage
    get "/docs/publish", DocsController, :publish
    get "/docs/tasks", DocsController, :tasks
    get "/docs/rebar3_usage", DocsController, :rebar3_usage
    get "/docs/rebar3_publish", DocsController, :rebar3_publish
    get "/docs/rebar3_private", DocsController, :rebar3_private
    get "/docs/rebar3_tasks", DocsController, :rebar3_tasks
    get "/docs/private", DocsController, :private
    get "/docs/faq", DocsController, :faq
    get "/docs/mirrors", DocsController, :mirrors
    get "/docs/public_keys", DocsController, :public_keys

    get "/policies/codeofconduct", PolicyController, :coc
    get "/policies/privacy", PolicyController, :privacy
    get "/policies/termsofservice", PolicyController, :tos
    get "/policies/copyright", PolicyController, :copyright
    get "/policies/dispute", PolicyController, :dispute

    get "/packages/:name/versions", VersionController, :index
    get "/packages/:repository/:name/versions", VersionController, :index

    get "/packages", PackageController, :index
    get "/packages/:name", PackageController, :show
    get "/packages/:name/:version", PackageController, :show
    get "/packages/:repository/:name/:version", PackageController, :show

    get "/blog", BlogController, :index
    get "/blog/:slug", BlogController, :show
  end

  scope "/dashboard", HexpmWeb.Dashboard do
    pipe_through :browser

    get "/profile", ProfileController, :index
    post "/profile", ProfileController, :update

    get "/password", PasswordController, :index, as: :dashboard_password
    post "/password", PasswordController, :update, as: :dashboard_password

    get "/email", EmailController, :index
    post "/email", EmailController, :create
    delete "/email", EmailController, :delete
    post "/email/primary", EmailController, :primary
    post "/email/public", EmailController, :public
    post "/email/resend", EmailController, :resend_verify
    post "/email/gravatar", EmailController, :gravatar

    get "/repos", OrganizationController, :redirect_repo
    get "/repos/*glob", OrganizationController, :redirect_repo
    get "/orgs/:dashboard_org", OrganizationController, :show
    post "/orgs/:dashboard_org", OrganizationController, :update
    post "/orgs/:dashboard_org/billing-token", OrganizationController, :billing_token
    post "/orgs/:dashboard_org/cancel-billing", OrganizationController, :cancel_billing
    post "/orgs/:dashboard_org/update-billing", OrganizationController, :update_billing
    post "/orgs/:dashboard_org/create-billing", OrganizationController, :create_billing
    post "/orgs/:dashboard_org/add-seats", OrganizationController, :add_seats
    post "/orgs/:dashboard_org/remove-seats", OrganizationController, :remove_seats
    post "/orgs/:dashboard_org/change-plan", OrganizationController, :change_plan
    post "/orgs/:dashboard_org/keys", OrganizationController, :create_key
    delete "/orgs/:dashboard_org/keys", OrganizationController, :delete_key
    get "/orgs/:dashboard_org/invoices/:id", OrganizationController, :show_invoice
    post "/orgs/:dashboard_org/invoices/:id/pay", OrganizationController, :pay_invoice
    get "/orgs", OrganizationController, :new
    post "/orgs", OrganizationController, :create

    get "/keys", KeyController, :index
    delete "/keys", KeyController, :delete
    post "/keys", KeyController, :create
  end

  scope "/", HexpmWeb do
    get "/sitemap.xml", SitemapController, :main
    get "/docs_sitemap.xml", SitemapController, :docs
    get "/hexsearch.xml", OpenSearchController, :opensearch
    get "/installs/hex.ez", InstallController, :archive
  end

  scope "/api", HexpmWeb.API, as: :api do
    pipe_through :upload

    for prefix <- ["/", "/repos/:repository"] do
      scope prefix do
        post "/publish", ReleaseController, :publish
        post "/packages/:name/releases", ReleaseController, :create
        post "/packages/:name/releases/:version/docs", DocsController, :create
      end
    end
  end

  scope "/api", HexpmWeb.API, as: :api do
    pipe_through :api

    get "/", IndexController, :index

    post "/users", UserController, :create
    get "/users/me", UserController, :me
    get "/users/me/audit_logs", UserController, :audit_logs
    get "/users/:name", UserController, :show
    # NOTE: Deprecated (2018-05-21)
    get "/users/:name/test", UserController, :test
    post "/users/:name/reset", UserController, :reset

    get "/orgs", OrganizationController, :index
    get "/orgs/:organization", OrganizationController, :show
    post "/orgs/:organization", OrganizationController, :update
    get "/orgs/:organization/audit_logs", OrganizationController, :audit_logs

    get "/orgs/:organization/members", OrganizationUserController, :index
    post "/orgs/:organization/members", OrganizationUserController, :create
    get "/orgs/:organization/members/:name", OrganizationUserController, :show
    post "/orgs/:organization/members/:name", OrganizationUserController, :update
    delete "/orgs/:organization/members/:name", OrganizationUserController, :delete

    get "/repos", RepositoryController, :index
    get "/repos/:repository", RepositoryController, :show

    for prefix <- ["/", "/repos/:repository"] do
      scope prefix do
        get "/packages", PackageController, :index
        get "/packages/:name", PackageController, :show
        get "/packages/:name/audit_logs", PackageController, :audit_logs

        get "/packages/:name/releases/:version", ReleaseController, :show
        delete "/packages/:name/releases/:version", ReleaseController, :delete

        post "/packages/:name/releases/:version/retire", RetirementController, :create
        delete "/packages/:name/releases/:version/retire", RetirementController, :delete

        get "/packages/:name/releases/:version/docs", DocsController, :show
        delete "/packages/:name/releases/:version/docs", DocsController, :delete

        get "/packages/:name/owners", OwnerController, :index
        get "/packages/:name/owners/:username", OwnerController, :show
        put "/packages/:name/owners/:username", OwnerController, :create
        delete "/packages/:name/owners/:username", OwnerController, :delete
      end
    end

    for prefix <- ["/", "/orgs/:organization"] do
      scope prefix do
        get "/keys", KeyController, :index
        get "/keys/:name", KeyController, :show
        post "/keys", KeyController, :create
        delete "/keys", KeyController, :delete_all
        delete "/keys/:name", KeyController, :delete
      end
    end

    get "/auth", AuthController, :show
  end

  if Mix.env() in [:dev, :test, :hex] do
    scope "/repo", HexpmWeb do
      get "/registry.ets.gz", TestController, :registry
      get "/registry.ets.gz.signed", TestController, :registry_signed
      get "/names", TestController, :names
      get "/versions", TestController, :version
      get "/installs/hex-1.x.csv", TestController, :installs_csv

      for prefix <- ["/", "/repos/:repository"] do
        scope prefix do
          get "/packages/:package", TestController, :package
          get "/tarballs/:ball", TestController, :tarball
        end
      end
    end

    scope "/api", HexpmWeb do
      pipe_through :api

      post "/repo", TestController, :repo
    end
  end

  def user_path(%User{organization: nil} = user) do
    Routes.user_path(Endpoint, :show, user)
  end

  def user_path(%User{organization: %Organization{} = organization}) do
    # Work around for path helpers with duplicate routes
    "/orgs/#{organization.name}"
  end

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    if report?(kind, reason) do
      conn = maybe_fetch_params(conn)
      url = "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}"

lib/hexpm_web/views/layout_view.ex
defmodule HexpmWeb.LayoutView do
  use HexpmWeb, :view

  def show_search?(assigns) do
    Map.get(assigns, :hide_search) != true
  end

  def title(assigns) do
    if title = Map.get(assigns, :title) do
      "#{title} | Hex"
    else
      "Hex"
    end
  end

  def description(assigns) do
    if description = Map.get(assigns, :description) do
      String.slice(description, 0, 160)
    else
      "A package manager for the Erlang ecosystem"
    end
  end

  def canonical_url(assigns) do
    if url = Map.get(assigns, :canonical_url) do
      tag(:link, rel: "canonical", href: url)
    else
      nil
    end
  end

  def search(assigns) do
    Map.get(assigns, :search)
  end

  def container_class(assigns) do
    Map.get(assigns, :container, "container")
  end

  def og_tags(assigns) do
    [
      tag(:meta, property: "og:title", content: Map.get(assigns, :title)),
      tag(:meta, property: "og:type", content: "website"),
      tag(:meta, property: "og:url", content: Map.get(assigns, :canonical_url)),
      tag(
        :meta,
        property: "og:image",
        content: Routes.static_url(HexpmWeb.Endpoint, "/images/favicon-160.png")
      ),
      tag(:meta, property: "og:image:width", content: "160"),
      tag(:meta, property: "og:image:height", content: "160"),
      tag(:meta, property: "og:description", content: description(assigns)),
      tag(:meta, property: "og:site_name", content: "Hex")
    ]
  end
end

lib/hexpm_web/templates/layout/_flash.html.eex
<div class="container flash">
  <%= if flash = get_flash(@conn, :error) do %>
    <div class="alert alert-danger" role="alert"><%=raw flash %></div>
  <% end %>
  <%= if flash = get_flash(@conn, :warning) do %>
    <div class="alert alert-warning" role="alert"><%= flash %></div>
  <% end %>
  <%= if flash = get_flash(@conn, :info) do %>
    <div class="alert alert-info" role="alert"><%= flash %></div>
  <% end %>
  <%= if flash = get_flash(@conn, :success) do %>
    <div class="alert alert-success" role="alert"><%= flash %></div>
  <% end %>
</div>

lib/hexpm_web/templates/layout/_read_only_mode.html.eex
<%= if Application.get_env(:hexpm, :read_only_mode, false) do %>
  <div class="read-only-mode" role="alert">
    <div class="container">
      Hex.pm is currently in read only mode due to maintainence,
      parts of the website may not work as expected
      but we will be back to normal operation in a few minutes.
    </div>
  </div>
<% end %>

lib/hexpm_web/templates/layout/app.html.eex
<%= render "header.html", assigns %>
<%= render @view_module, @view_template, assigns %>
<%= render "footer.html", assigns %>

lib/hexpm_web/templates/layout/footer.html.eex
    </div>
    </section>

    <div class="footer">
      <div class="footer-nav">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <h4>About Hex</h4>
              <ul>
                <li><a href="<%= Routes.page_path(Endpoint, :about) %>">About</a></li>
                <li><a href="<%= Routes.blog_path(Endpoint, :index) %>">Blog</a></li>
                <li><a href="<%= Routes.page_path(Endpoint, :sponsors) %>">Sponsors</a></li>
                <li><a href="https://github.com/hexpm">GitHub</a></li>
                <li><a href="https://twitter.com/hexpm">Twitter</a></li>
              </ul>
            </div>

            <div class="col-md-4">
              <h4>Help</h4>
              <ul>
                <li><a href="<%= Routes.docs_path(Endpoint, :index) %>">Documentation</a></li>
                <li><a href="https://github.com/hexpm/specifications">Specifications</a></li>
                <li><a href="https://github.com/hexpm/hex/issues">Report Client Issue</a></li>
                <li><a href="https://github.com/hexpm/hexpm/issues">Report General Issue</a></li>
                <li><a href="mailto:support@hex.pm">Contact Support</a></li>
              </ul>
            </div>

            <div class="col-md-4">
              <h4>Policies and Terms</h4>
              <ul>
                <li><a href="<%= Routes.policy_path(Endpoint, :coc) %>">Code of Conduct</a></li>
                <li><a href="<%= Routes.policy_path(Endpoint, :tos) %>">Terms of Service</a></li>
                <li><a href="<%= Routes.policy_path(Endpoint, :privacy) %>">Privacy Policy</a></li>
                <li><a href="<%= Routes.policy_path(Endpoint, :copyright) %>">Copyright Policy</a></li>
                <li><a href="<%= Routes.policy_path(Endpoint, :dispute) %>">Dispute Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="<%= Routes.static_path(Endpoint, "/js/app.js") %>"></script>

  </body>
</html>

lib/hexpm_web/templates/layout/header.html.eex
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= description(assigns) %>">

    <title><%= title(assigns) %></title>

    <%= og_tags(assigns) %>

    <link rel="search" type="application/opensearchdescription+xml" title="Hex" href="/hexsearch.xml">
    <link rel="stylesheet" href="<%= Routes.static_path(Endpoint, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(Endpoint, "/favicon.png") %>">
  </head>
  <body>
    <!--[if lt IE 10]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <section class="content-wrapper">
    <%= render "_read_only_mode.html" %>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img src="<%= Routes.static_path(Endpoint, "/images/hex.png") %>" srcset="<%= Routes.static_path(Endpoint, "/images/hex.png") %> 1x, <%= Routes.static_path(Endpoint, "/images/hex@2.png") %> 2x, <%= Routes.static_path(Endpoint, "/images/hex@3.png") %> 3x" alt="hex logo">
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <%= if show_search?(assigns) do %>
          <form class="navbar-form pull-left-non-mobile" role="search" action="<%= Routes.package_path(Endpoint, :index) %>">
             <div class="input-group">
                <input placeholder="Find packages" name="search" type="text" class="form-control" value="<%= search(assigns) %>">
                <input type="hidden" name="sort" value="recent_downloads">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-search" tabindex="1">
                    <%= icon(:glyphicon, :search) %>
                  </button>
                </div>
             </div>
          </form>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= Routes.package_path(Endpoint, :index) %>">Packages</a></li>
            <li><a href="<%= Routes.page_path(Endpoint, :pricing) %>">Pricing</a></li>
            <li><a href="<%= Routes.docs_path(Endpoint, :index) %>">Docs</a></li>

            <%= if logged_in?(assigns) do %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= @current_user.username %>
                  <img src="<%= gravatar_url(User.email(@current_user, :gravatar), :small) %>" class="navbar-avatar">
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="<%= Routes.user_path(Endpoint, :show, @current_user) %>">Profile</a></li>
                  <li><a href="<%= Routes.profile_path(Endpoint, :index) %>">Dashboard</a></li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= form_tag(Routes.login_path(Endpoint, :delete)) do %>
                      <button type="submit" class="btn btn-link">Log out</button>
                    <% end %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><a href="<%= Routes.login_path(Endpoint, :show) %>">Log in</a></li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <%= unless assigns[:error] || assigns[:custom_flash] do %>
      <%= render "_flash.html", conn: @conn %>
    <% end %>

    <div class="<%= container_class(assigns) %>">

lib/hexpm_web/templates/layout/simple_header.html.eex
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= description(assigns) %>">

    <title><%= title(assigns) %></title>

    <%= og_tags(assigns) %>

    <link rel="search" type="application/opensearchdescription+xml" title="Hex" href="/hexsearch.xml">
    <link rel="stylesheet" href="<%= Routes.static_path(Endpoint, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(Endpoint, "/favicon.png") %>">
  </head>
  <body>
    <!--[if lt IE 10]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <section class="content-wrapper">
    <%= render "_read_only_mode.html" %>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <img src="<%= Routes.static_path(Endpoint, "/images/hex.png") %>" srcset="<%= Routes.static_path(Endpoint, "/images/hex.png") %> 1x, <%= Routes.static_path(Endpoint, "/images/hex@2.png") %> 2x, <%= Routes.static_path(Endpoint, "/images/hex@3.png") %> 3x" alt="hex logo">
          </a>
        </div>
      </div>
    </nav>

    <div class="<%= container_class(assigns) %>">